acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls")),
    path('book/', include("book.urls")),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel, name="cancel"),
    path('create', views.create, name="create"),
    path('delete/<tpk>', views.delete, name="delete"),
]

vote/models.py
from distutils.command.upload import upload
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject
    
    def summary(self):
        if len(self.content) > 10:
            return f"{self.content[:10]} ..."
        return self.content


class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    pic = models.ImageField(upload_to="vote/%y/%m")
    con = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.topic}_{self.name}"

vote/views.py
from django.shortcuts import redirect, render
from .models import Topic, Choice
from django.utils import timezone
from django.contrib import messages

# Create your views here.
def delete(req, tpk):
    t = Topic.objects.get(id=tpk)
    # c = t.choice_set.all()
    if req.user == t.maker:
        t.delete()
        # c.pic.delete()
    else:
        messages.warning(req, "투표글삭제에 고의적 접근으로 인한 해킹일 경우 법적처벌을 받을 수 있습니다.")
    return redirect("vote:index")


def create(req):
    if req.method == "POST":
        s = req.POST.get("sub")
        c = req.POST.get("con")
        cn = req.POST.getlist("chn")
        cf = req.FILES.getlist("chf")   # INPUT TYPE FILE 일때!!
        cc = req.POST.getlist("chc")
        # print(s,c,cn,cf,cc)
        t = Topic(subject=s, maker=req.user, content=c, pubdate=timezone.now())
        t.save()
        for name, pic, con in zip(cn, cf, cc):
            Choice(topic=t, name=name, pic=pic, con=con).save()
        return redirect("vote:index")
    return render(req, "vote/create.html")


def cancel(req, tpk):
    t = Topic.objects.get(id=tpk)
    t.voter.remove(req.user)
    # 사용자 기준 투표한 모든값 중 현재 토픽에 대한 투표값
    req.user.choice_set.get(topic=t).choicer.remove(req.user)
    return redirect("vote:detail", tpk)


def vote(req, tpk):
    t = Topic.objects.get(id=tpk)
    if not req.user in t.voter.all():   # 다중투표 불가
        t.voter.add(req.user)
        cpk = req.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(req.user)
    return redirect("vote:detail", tpk)


def detail(req, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t" : t,
        "cset" : c
    }
    return render(req, "vote/detail.html", context)


def index(req):
    t = Topic.objects.all()
    context ={
        "tset" : t,
    }
    return render(req, "vote/index.html", context)

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>토픽생성</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="sub" class="form-control mt-5" placeholder="TOPIC 제목을 입력하세요" />
            <textarea name="con" class="form-control mt-4" placeholder="TOPIC 에 관해서 간단하게 설명해주세요" style="height: 150px;"></textarea>
            <div class="text-end mt-4">
                <button class="btn btn-secondary" type="button" onclick="makesel()">보기생성</button>
                <button class="btn btn-dark">토픽생성</button>
            </div>
            <div id="here" class="row mt-5"></div>
        </form>
    </div>

    <script>
        function makesel(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-lg-4 mt-5");
            n.innerHTML = '<input type="text" name="chn" class="form-control" placeholder="보기이름입력" />\
                <input type="file" name="chf" class="form-control mt-3 mb-3" />\
                <textarea name="chc" placeholder="보기설명" class="form-control"></textarea>';
            d.appendChild(n);
        }
    </script>
{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>{{ t.subject }}</b></h1>
        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control" style="height:200px;" disabled>{{ t.content }}</textarea>
            </div>
            <div class="col-lg-4">
                <img src="{{ t.maker.getpic }}" width="100%" />
                <div class="mt-3 text-center">
                    <h4>BY. {{ t.maker }}</h4>
                </div>
                <div class="mt-3 text-end">
                    <h5>{{ t.pubdate|date:'Y년 n월 j일' }}</h5>
                </div>
            </div>
        </div>

        {% if user in t.voter.all %}
            <div class="row mt-5">
                {% for i in cset %}
                <div class="col-lg-4">
                    <img src="{{ i.pic.url }}" width="100%">
                    <div class="text-center mt-3 mb-3">
                        <h5><b>{{ i.name }}</b></h5>
                    </div>
                    <div class="progress mt-2 mb-2">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:{{ i.choicer.count|div:t.voter.count|mul:100 }}%">
                            {{ i.choicer.count|div:t.voter.count|mul:100 }} %
                        </div>
                    </div>
                    <textarea class="form-control" style="height:80px;" disabled>{{ i.con }}</textarea>
                </div>
                {% endfor %}
            </div>
            <div class="text-end mt-4 mb-5">
                <a href="{% url 'vote:cancel' t.id %}" class="btn btn-danger btn-lg">투표취소</a>
            </div>
        {% else %}
            <form method="post" action="{% url 'vote:vote' t.id %}">
                {% csrf_token %}
                <div class="row mt-5">
                    {% for i in cset %}
                    <div class="col-lg-4">
                        <input class="form-check-input" type="radio" {% if forloop.first %} checked {% endif %} name="cho" value="{{i.id}}" name="flexRadioDefault" id="flexRadioDefault1" />
                        <img src="{{ i.pic.url }}" width="100%">
                        <div class="text-center mt-3 mb-3">
                            <h5><b>{{ i.name }}</b></h5>
                        </div>
                        <textarea class="form-control" style="height:80px;" disabled>{{ i.con }}</textarea>
                    </div>
                    {% endfor %}
                </div>
                <div class="text-end mt-4 mb-5">
                    <button class="btn btn-dark btn-lg">투표하기</button>
                </div>
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>VOTE</b></h1>
        <div class="text-end mb-3">
            <a href="{% url 'vote:create' %}" class="btn btn-dark btn-lg">TOPIC생성</a>
        </div>
        <div class="row">
            {% for i in tset %}
                <div class="col-lg-4">
                    <div class="card">
                        <img src="{{ i.maker.getpic }}" class="card-img-top" alt="">
                        
                        <div class="card-body" {% if user in i.voter.all %} style="background-color: rgb(245, 238, 225);" {% endif %}>
                            <h5 class="card-title text-center"><b>{{ i.subject }}</b></h5>
                            <p class="card-text">{{ i.summary }}</p>
                            <a href="{% url 'vote:detail' i.id %}" class="btn btn-dark">{% if user in i.voter.all %}결과보기{% else %}투표하러가기{% endif %}</a>
                            {% if user == i.maker %}
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#topic{{forloop.counter}}">
                                    토픽삭제
                                </button>
                            {% endif %}
                        </div>
                        
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% for i in tset %}
        <div class="modal fade" id="topic{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">토픽삭제 안내</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <b>{{ i.voter.count }}</b> 명의 투표 참여자가 있습니다.<br />
                        삭제 하시겠습니까?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                        <a href="{% url 'vote:delete' i.id %}" class="btn btn-danger">삭제</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}