acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls")),
    path('book/', include("book.urls")),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to="user/%y/%m")
    age = models.IntegerField(default=1)
    comment = models.TextField()

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/user/noimage.png"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User
from django.contrib import messages

# Create your views here.
def delete(req):
    pw = req.POST.get("pwck")
    if check_password(pw, req.user.password):
        req.user.delete()
        return redirect("acc:index")
    else:
        messages.error(req, "패스워드가 틀렸습니다.")
        return redirect("acc:profile")

def update(req):
    if req.method == "POST":
        u = req.user
        up = req.POST.get("upass")
        uc = req.POST.get("ucomm")
        pi = req.FILES.get("upic")
        ue = req.POST.get("umail")
        if up:
            u.set_password(up)  # 비번 암호화 수정
        if pi:
            u.pic = pi
        u.comment = uc
        u.email = ue
        u.save()
        login(req,u)
        return redirect("acc:profile")
    return render(req, "acc/update.html")


def signup(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")
        uc = req.POST.get("ucomm")
        pi = req.FILES.get("upic")
        User.objects.create_user(username=un,password=up,comment=uc,pic=pi)
        return redirect("acc:login")
    return render(req, "acc/signup.html")


def profile(req):
    return render(req, "acc/profile.html")


def logout_user(req):
    logout(req) # request 에 실린 user 빼냄
    return redirect("acc:index")


def login_user(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")

        # authenticate 는 사용자의 username, password 통해 인증
        u = authenticate(username=un, password=up)
        if u:   # 로그인 성공했을 떄
            login(req, u)
            messages.success(req, f"{u}! WELCOME~")
            return redirect("acc:index")
        else:
            messages.error(req, "계정정보가 일치하지 않습니다.")
    return render(req, "acc/login.html")


def index(req):
    return render(req, "acc/index.html")

templates/acc/index.html
{% extends 'base.html' %}
{% block con %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">김치찌개 좋아하시는 분 ~~ </h1>
            <p class="col-md-8 fs-4">WELCOME! {{ user }} ★</p>
            <a href=""><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">CLICK</button></a>
        </div>
    </div>
{% endblock %}
{% block noauth %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">김치찌개 좋아하시는 분 ~~ </h1>
            <p class="col-md-8 fs-4">WELCOME! {{ user }} ★</p>
        </div>
    </div>
{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block noauth %}
    <div class="container mt-5 mb-5">
        <h1>로그인</h1>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="uname" placeholder="아이디 입력" class="form-control mt-5 mb-3" />
            <input type="password" name="upass" placeholder="비밀번호 입력" class="form-control" />
            <div class="text-end mt-5">
                <a href="{% url 'acc:index' %}"><button type="button" class="btn btn-secondary">취소</button></a> 
                <button class="btn btn-primary">LOGIN</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>프로필</b></h1>

        <div class="text-center mt-5">
            <img src="{{ user.getpic }}" class="rounded-circle" height="250px" />
        </div>

        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" value="{{ user }}" disabled class="form-control" style="font-weight: bold;" />
        </div>
        <div class="mb-3">
            <label class="form-label">AGE</label>
            <input type="text" value="{{ user.age }}" style="font-weight: bold;" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label class="form-label">EMAIL</label>
            <input type="text" value="{{ user.email }}" style="font-weight: bold;" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{ user.comment }}</textarea>
        </div>

        <div class="text-end">
            <a href="{% url 'acc:update' %}" class="btn btn-dark">정보수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">계정삭제</button>
        </div>
    </div>

    <!-- 계정삭제 알림창 -->
    <form method="post" action="{% url 'acc:delete' %}">
        {% csrf_token %}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title" id="exampleModalLabel"><b>계정삭제 알림창</b></h3>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div>
                            <h4><b>패스워드 확인</b></h4>
                            <input name="pwck" class="form-control mt-3" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-danger">삭제</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block noauth %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="container mt-5 mb-5" style="font-weight: bold; font-size: 20px;">
            <h1><b>회원가입</b></h1>
            <div class="mb-3 mt-5">
                <label class="form-label">USERNAME</label>
                <input type="text" name="uname" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">PASSWORD</label>
                <input type="password" name="upass" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">COMMENT</label>
                <textarea name="ucomm" class="form-control"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">USERPIC</label>
                <input type="file" name="upic" class="form-control" id="exampleInputPassword1" />
            </div>
            <div class="mt-4 text-end">
                <button class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
            </div>
        </div>
    </form>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container mt-5 mb-5"  style="font-size: 20px; font-weight: bold;">
            <h1><b>정보수정</b></h1>
    
            <div class="mb-3 mt-5">
                <label class="form-label">USERNAME</label>
                <input type="text" value="{{ user }}" disabled class="form-control" />
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
                <input type="password" name="upass" class="form-control" />
            </div>
            <div class="mb-3 mt-5">
                <label class="form-label">EMAIL</label>
                <input type="text" name="umail" value="{{ user.email }}" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">COMMENT</label>
                <textarea name="ucomm" class="form-control">{{ user.comment }}</textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">USERPIC</label>
                <input type="file" name="upic" class="form-control" />
            </div>
            <div class="text-end">
                <a href="{% url 'acc:profile' %}"><button type="button" class="btn btn-dark">BACK</button></a>
                <button class="btn btn-dark">UPDATE</button>
            </div>
        </div>
    </form>
{% endblock %}