acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('rlikey/<bpk>', views.rlikey, name="rlikey"),
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls")),
    path('book/', include("book.urls")),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

trans/urls.py
from django.urls import path
from . import views

app_name = "trans"
urlpatterns = [
    path('index/', views.index, name="index"),
]

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel, name="cancel"),
    path('create', views.create, name="create"),
    path('delete/<tpk>', views.delete, name="delete"),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>DJANGO PROJECT</title>
</head>
<body>
    <!--//NAV BAR-->
    {% if user.is_authenticated %}
    <!--인증된 사용자-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'acc:index' %}">DJANGO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">BOARD</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'trans:index' %}">TRANS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'vote:index' %}">VOTE</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'book:index' %}">BOOKMAKR</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% else %}
    <!--익명의 사용자-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'acc:index' %}">DJANGO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="">1</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="">2</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endif %}
    <!--NAV BAR//-->

    {% for i in messages %}
        <div class="alert {{i.tags}} alert-dismissible fade show" role="alert">
            <strong>{{ i.tags|upper }}</strong> {{ i.message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <!--//인증된 사용자-->
    {% if user.is_authenticated %}
        {% block con %}
            <div class="container mt-5 mb-5 text-center">
                <h1><b>이미 인증된 사용자입니다.</b></h1>
                <div class="mt-5">
                    <a class="btn btn-dark btn-lg" href="{% url 'board:index' %}">게시판</a>
                    <a class="btn btn-dark btn-lg" href="{% url 'trans:index' %}">번역기</a>
                    <a class="btn btn-dark btn-lg" href="{% url 'vote:index' %}">투표소</a>
                    <a class="btn btn-dark btn-lg" href="{% url 'book:index' %}">투표소</a>
                </div>
            </div>
        {% endblock %}
    <!--//인증되지 않은 사용자-->
    {% else %}
        {% block noauth %}
            <div class="container mt-5 mb-5 text-center">
                <h1><b>로그인이 필요한 페이지 입니다!!</b></h1>
                <div class="mt-5">
                    <a class="btn btn-dark btn-lg" href="{% url 'acc:login' %}">로그인</a>
                </div>
            </div>
        {% endblock %}
    {% endif %}
    
    <style>
        .alert { background-color: whitesmoke; }
        .success { background-color: blue; }
        .warning { background-color: yellow; }
        .info { background-color: gray; }
        .error { background-color: red; }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>