acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('rlikey/<bpk>', views.rlikey, name="rlikey"),
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls")),
    path('book/', include("book.urls")),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

board/models.py
import re
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")   # User 의 DB를 바라봄
    content = models.TextField()
    pubdate = models.DateTimeField()    # 최신글이 맨위로 올라오기 위해
    likey = models.ManyToManyField(User, blank=True, related_name="likey")    # N 대 N 관계

    def __str__(self):
        return self.subject
    
    def summary(self):
        if len(self.content) > 40:
            return f"{self.content[:40]}..."
        return self.content
    
    def hot(self):
        if self.likey.count() >= 2:
            return True
        return False


class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.board}_{self.replyer}"

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages

# Create your views here.
def rlikey(req, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(req.user)
    return redirect("board:detail", bpk)


def likey(req, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(req.user)
    return redirect("board:detail", bpk)


def dreply(req, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == req.user:
        r.delete()
    else:
        messages.warning(req, "답변삭제에 고의적 접근으로 인한 해킹일 경우 법적처벌을 받을 수 있습니다.")
    return redirect("board:detail", bpk)


def creply(req, bpk):
    b = Board.objects.get(id=bpk)
    r = req.POST.get("rcom")
    Reply(board=b, replyer=req.user, comment=r).save()
    return redirect("board:detail", bpk)


def update(req, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer != req.user:
        return redirect(req, "board:index")
    if req.method == "POST":
        s = req.POST.get("bsub")
        c = req.POST.get("bcon")
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:detail", bpk)
    context = {
        "b" : b
    }
    return render(req, "board/update.html", context)


def create(req):
    if req.method == "POST":
        s = req.POST.get("bsub")
        c = req.POST.get("bcon")
        Board(subject=s, writer=req.user, content=c, pubdate=timezone.now()).save()
        return redirect("board:index")
    return render(req, "board/create.html")


def delete(req, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == req.user:
        messages.info(req, "글삭제가 정상적으로 완료되었습니다.")
        b.delete()
    else:   # HACKING
        messages.warning(req, "글삭제에 고의적 접근으로 인한 해킹일 경우 법적처벌을 받을 수 있습니다.")
    return redirect("board:index")


def detail(req, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b" : b,
        "rset" : r
    }
    return render(req, "board/detail.html", context)


def index(req):
    pg = req.GET.get("page",1)
    cate = req.GET.get("cate", "")
    kw = req.GET.get("kw", "")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)  # 작성자를 회원으로 검색
            except:
                b = Board.objects.none()    # 아무것도 없는 레코드 설정
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            pass
    else:
        b = Board.objects.all()
    
    b = b.order_by('-pubdate')   # 최신글 위로
    
    pag = Paginator(b, 5)
    obj = pag.get_page(pg)
    context = {
        "bset" : obj,
        "cate" : cate,
        "kw" : kw,
    }
    return render(req, "board/index.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시글 작성</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="bsub" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" value="{{ user }}" disabled class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea name="bcon" class="form-control" style="height: 150px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1>{{ b.subject }}</h1>
        <div class="row mt-5 mb-3">
            <div class="col-lg-8">
                <textarea class="form-control" disabled style="height:240px;">{{ b.content }}</textarea>
            </div>
            <div class="col-lg-4 text-center">
                <img src="{{ b.writer.getpic }}" class="rounded-circle" height="180px" />
                <h4 class="mt-3">written by. <b>{{ b.writer }}</b></h4>
            </div>
            <div class="text-end text-secondary">
                {{ b.pubdate | date:'Y년 m월 d일 H:i:s'}}
            </div>
        </div>

        <div class="text-end mt-4">
            <a href="{% url 'board:index' %}" class="btn btn-dark">글목록</a>
            {% if b.writer == user %}
                <a href="{% url 'board:update' b.id %}" class="btn btn-secondary">글수정</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#remove">글삭제</button>
            {% endif %}

            {% if user in b.likey.all %}
                <a href="{% url 'board:rlikey' b.id %}" class="btn btn-danger">좋아요취소</a>
            {% else %}
                <a href="{% url 'board:likey' b.id %}" class="btn btn-primary">좋아요♥</a>
            {% endif %}

            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#star">즐겨찾기추가</button>
        </div>
        
        <!--//댓글작성-->
        <hr>
        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class="row mt-3 mb-5">
                <div class="col-lg-10">
                    <input type="text" name="rcom" class="form-control" />
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-dark" style="width:100%;">댓글생성</button>
                </div>
            </div>
        </form>
        
        {% if rset %}
            {% for i in rset %}
                <div class="row mt-3" style="border-bottom:1px dotted #555">
                    <div class="col-lg-2 mb-3 text-center">
                        <img src="{{ i.replyer.getpic }}" class="rounded-circle" height="130px" />
                        <div>
                            <b>{{ i.replyer }}</b>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <textarea disabled class="form-control" style="height:100px;">{{ i.comment }}</textarea>
                        <div class="text-end mt-3">
                            {% if i.replyer == user %}
                                <a href="{% url 'board:dreply' b.id i.id %}" class="btn btn-sm btn-danger">댓글삭제</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4 class="text-center">첫번째 댓글을 작성해 주세요.</h4>
        {% endif %}
    </div>

    <!-- 삭제 Modal -->
    <div class="modal fade" id="remove" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">게시글 삭제</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <h4>게시글을 정말 삭제 하시겠습니까?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}" class="btn btn-danger">삭제</a>
                </div>
            </div>
        </div>   
    </div>

    <!-- 즐겨찾기 Modal -->
    <div class="modal fade" id="star" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">즐겨찾기 안내</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'book:create' %}">
                    {% csrf_token %}
                    <div class="modal-body text-center">
                        <div class="text-end mb-3">
                            <input type="checkbox" name="impo" class="btn-check" id="btn-check-outlined" autocomplete="off" />
                            <label class="btn btn-outline-warning" for="btn-check-outlined">★</label><br />
                        </div>
                        <textarea name="scon" class="form-control" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                        <input type="hidden" name="sname" value="[게시판] {{ b.subject }}" />
                        <input type="hidden" name="surl" value="{{ request.path }}" />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-dark">생성</button>
                    </div>
                </form>
            </div>
        </div>   
    </div>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

    {% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>게시판</b></h1>
        <div class="text-end">
            <a href="{% url 'board:create' %}" class="btn btn-dark">CREATE</a>
        </div>
        <table class="table table-hover mt-5 text-center">
            <thead>
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                    <th scope="col">LIKEY</th>
                </tr>
            </thead>
            <tbody>
                {% if bset %}
                    {% for i in bset %}
                    <tr {% if i.hot %} style="background-color:antiquewhite" {% endif %}>
                        <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                        <td class="text-start"><a href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                        <td class="text-start">{{ i.summary }}</td>
                        <td>{{ i.writer }}</td>
                        <td>{{ i.likey.count }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                <tr>
                    <td colspan="5" class="text-center" style="padding:50px 0">
                        {% if kw %}
                            <h3>검색 결과가 없습니다.</h3>
                        {% else %}
                        <h3>첫번째 게시글글을 작성해 주세요.</h3>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
        <nav aria-label="Page navigation example" class="mt-5">
            <ul class="pagination justify-content-center">
                {% if bset.has_previous %}
                    <li class="page-item">
                        <a href="{% url 'board:index' %}?page=1&kw={{kw}}&cate={{cate}}" class="page-link">H</a>
                    </li>
                    <li class="page-item">
                        <a href="{% url 'board:index' %}?page={{bset.previous_page_number}}&kw={{kw}}&cate={{cate}}" class="page-link">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">H</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">Previous</a>
                    </li>
                {% endif %}
                
                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                        <li class="page-item {% if i == bset.number %} active {% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&kw={{kw}}&cate={{cate}}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
    
                {% if bset.has_next %}
                    <li class="page-item">
                        <a href="{% url 'board:index' %}?page={{bset.next_page_number}}&kw={{kw}}&cate={{cate}}" class="page-link">Next</a>
                    </li>
                    <li class="page-item">
                        <a href="{% url 'board:index' %}?page={{bset.paginator.num_pages}}&kw={{kw}}&cate={{cate}}" class="page-link">E</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Next</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">E</a>
                    </li>
                {% endif %}
                </li>
            </ul>
        </nav>
        <form>
            <div class="row mt-4">
                <div class="col-lg-2"></div>
                <div class="col-lg-2">
                    <select name="cate" class="form-select" aria-label="">
                        <option value="sub" {% if cate == "sub" %}selected{% endif %}>제목</option>
                        <option value="wri" {% if cate == "wri" %}selected{% endif %}>작성자</option>
                        <option value="con" {% if cate == "con" %}selected{% endif %}>내용</option>
                    </select>
                </div>
                <div class="col-lg-5">
                    <input type="text" name="kw" value="{{ kw }}" class="form-control" />
                </div>
                <div class="col-lg-1 text-center">
                    <button class="btn btn-dark">검색</button>
                </div>
                <div class="col-lg-2"></div>
            </div>
        </form>
    </div>
{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시글 수정</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="bsub" value="{{ b.subject }}" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" value="{{ b.writer }}" disabled class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea name="bcon" class="form-control" style="height: 150px;">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정</button>
            </div>
        </form>
    </div>
{% endblock %}